/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './categories.component';
const styles_CategoriesComponent:any[] = ([] as any[]);
export const RenderType_CategoriesComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CategoriesComponent,
  data: {}
}
);
export function View_CategoriesComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['Categories']))],(null as any),(null as any));
}
function View_CategoriesComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_CategoriesComponent_0,RenderType_CategoriesComponent)),
    import0.ɵdid(24576,(null as any),0,import1.CategoriesComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CategoriesComponentNgFactory:import0.ComponentFactory<import1.CategoriesComponent> = import0.ɵccf('ng-component',import1.CategoriesComponent,View_CategoriesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvY2F0ZWdvcmllcy9jYXRlZ29yaWVzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9kZXYvQ2hlY2tpbmdBY2NvdW50L3NyYy9hcHAvYmFua2luZy9jYXRlZ29yaWVzL2NhdGVnb3JpZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvY2F0ZWdvcmllcy9jYXRlZ29yaWVzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvY2F0ZWdvcmllcy9jYXRlZ29yaWVzLmNvbXBvbmVudC50cy5DYXRlZ29yaWVzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiQ2F0ZWdvcmllcyIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQ0FBOzs7O0lDQUE7Z0JBQUE7Ozs7In0=
