/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './budget.component';
const styles_BudgetComponent:any[] = ([] as any[]);
export const RenderType_BudgetComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_BudgetComponent,
  data: {}
}
);
export function View_BudgetComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['Budget']))],(null as any),(null as any));
}
function View_BudgetComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_BudgetComponent_0,RenderType_BudgetComponent)),
    import0.ɵdid(24576,(null as any),0,import1.BudgetComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const BudgetComponentNgFactory:import0.ComponentFactory<import1.BudgetComponent> = import0.ɵccf('ng-component',import1.BudgetComponent,View_BudgetComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvYnVkZ2V0L2J1ZGdldC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvYnVkZ2V0L2J1ZGdldC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9kZXYvQ2hlY2tpbmdBY2NvdW50L3NyYy9hcHAvYmFua2luZy9idWRnZXQvYnVkZ2V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvYnVkZ2V0L2J1ZGdldC5jb21wb25lbnQudHMuQnVkZ2V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiQnVkZ2V0IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7eUJDQUE7Ozs7SUNBQTtnQkFBQTs7OzsifQ==
