/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './accounts.component';
const styles_AccountsComponent:any[] = ([] as any[]);
export const RenderType_AccountsComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AccountsComponent,
  data: {}
}
);
export function View_AccountsComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['Accounts']))],(null as any),(null as any));
}
function View_AccountsComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_AccountsComponent_0,RenderType_AccountsComponent)),
    import0.ɵdid(24576,(null as any),0,import1.AccountsComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AccountsComponentNgFactory:import0.ComponentFactory<import1.AccountsComponent> = import0.ɵccf('ng-component',import1.AccountsComponent,View_AccountsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvYWNjb3VudHMvYWNjb3VudHMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2Rldi9DaGVja2luZ0FjY291bnQvc3JjL2FwcC9iYW5raW5nL2FjY291bnRzL2FjY291bnRzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L2Rldi9DaGVja2luZ0FjY291bnQvc3JjL2FwcC9iYW5raW5nL2FjY291bnRzL2FjY291bnRzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovZGV2L0NoZWNraW5nQWNjb3VudC9zcmMvYXBwL2JhbmtpbmcvYWNjb3VudHMvYWNjb3VudHMuY29tcG9uZW50LnRzLkFjY291bnRzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiQWNjb3VudHMiLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
